### ISSUE TITLE
project creation window

### ISSUE THREAD

**Issue by MythicLegendary** [MythicLegendary/EE461L-Project#15]
After the user presses the project creation button, a project window should exist in which the user should be able to create new projects by giving them a name, description and ID. Duplicate IDs should be denied.

**Comment by stephen-petrick** [comment]
Created two separate issues, one for displaying current projects and another to start project creation via a button. Edit this one to what the project creation screen allows (i.e what happens when the button for project creation is pressed).

**Comment by MythicLegendary** [comment]
Feature created successfully.
