### ISSUE TITLE
Update error handling in Database API

### ISSUE THREAD

**Issue by snivy2901** [MythicLegendary/EE461L-Project#51]
The current database API only handles 0 and -1 for error checking and print functions with error info.

Update error handling for frontend usage.

Possible ideas:
Create object file for error handling/Create new exception handling (Java implementation)
Return String for each function, handle error processing in "frontend"

**Comment by snivy2901** [comment]
https://github.com/MythicLegendary/EE461L-Project/issues/47

**Comment by snivy2901** [comment]
https://github.com/MythicLegendary/EE461L-Project/issues/49

**Comment by MythicLegendary** [comment]
Errors handled on each page on the front end individually.
