### ISSUE TITLE
Hardware Resource Check-in Button

### ISSUE THREAD

**Issue by MythicLegendary** [MythicLegendary/EE461L-Project#9]
I should be able to check in resources by specifying what I want to check in and clicking a button.

**Comment by stephen-petrick** [comment]
Management interface will be updated real-time to reflect current state of of resource allocation

**Comment by stephen-petrick** [comment]
Edited to contain only the sentence containing the check-in button. Moved others to separate and individual issues.

**Comment by MythicLegendary** [comment]
Feature created successfully.
